GET http://localhost:4000/users HTTP/1.1
###

GET http://localhost:4000/users/20 HTTP/1.1

###

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "alexander2",
    "apellidos": "diaz2",
    "edad": 31,
    "email": "adriana@hotmail.com",
    "id": 40
}

### UPDATE

PUT http://localhost:4000/users/40 HTTP/1.1
Content-Type: application/json

{
    "nombre": "prueba 2 de update",
    "apellidos": "hola",
    "edad": 31,
    "email": "adriana@hotmail.com",
    "id": 30
}

### delete

DELETE http://localhost:4000/users/20 HTTP/1.1